[package]
name = "abbrws"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
hyper = "0.13.1"
http = "0.2.0"
tokio = { version="0.2.9", features=["rt-threaded", "macros"] }
digest_auth = "0.2.1"
future-utils = "0.12.1"
